// Login actions
const LOGIN = 'LOGIN';
const LOGOUT = 'LOGOUT';
const GET_USER_INFORMATION = 'GET_USER_INFORMATION';
const LOGIN_LOADING = 'LOGIN_LOADING';
const LOGIN_ERROR_REQUEST = 'LOGIN_ERROR_REQUEST';

// Redux actions
const INCREASE = 'INCREASE';
const DECREASE = 'DECREASE';

export default {
  INCREASE,
  DECREASE,
  LOGIN,
  LOGOUT,
  GET_USER_INFORMATION,
  LOGIN_LOADING,
  LOGIN_ERROR_REQUEST
};
