// User actions
const LOGIN = 'LOGIN';
const LOGOUT = 'LOGOUT';
const GET_USER_INFORMATION = 'GET_USER_INFORMATION';
const LOGIN_LOADING = 'LOGIN_LOADING';
const LOGIN_ERROR_REQUEST = 'LOGIN_ERROR_REQUEST';

// Redux actions
const INCREASE = 'INCREASE';
const DECREASE = 'DECREASE';

// Offer actions
const FETCH_OFFER = 'FETCH_OFFER';
const LOAD_MORE_OFFER = 'LOAD_MORE_OFFER';
const FETCH_OFFER_LOADING = 'FETCH_OFFER_LOADING';
const FETCH_OFFER_ERROR = 'FETCH_OFFER_ERROR';
const RESET_OFFER = 'RESET_OFFER';
const FETCH_DETAIL_OFFER = 'FETCH_DETAIL_OFFER';
const FETCH_DETAIL_OFFER_LOADING = 'FETCH_DETAIL_OFFER_LOADING';
const FETCH_DETAIL_OFFER_ERROR = 'FETCH_DETAIL_OFFER_ERROR';
const RESET_DETAIL_OFFER = 'RESET_DETAIL_OFFER';

export default {
  INCREASE,
  DECREASE,
  LOGIN,
  LOGOUT,
  GET_USER_INFORMATION,
  LOGIN_LOADING,
  LOGIN_ERROR_REQUEST,
  FETCH_OFFER,
  FETCH_DETAIL_OFFER,
  FETCH_OFFER_ERROR,
  FETCH_DETAIL_OFFER_ERROR,
  FETCH_OFFER_LOADING,
  FETCH_DETAIL_OFFER_LOADING,
  RESET_DETAIL_OFFER,
  RESET_OFFER,
  LOAD_MORE_OFFER
};
