// User actions
const LOGIN = 'LOGIN';
const LOGOUT = 'LOGOUT';
const GET_USER_INFORMATION = 'GET_USER_INFORMATION';
const LOGIN_LOADING = 'LOGIN_LOADING';
const LOGIN_ERROR_REQUEST = 'LOGIN_ERROR_REQUEST';

// Redux actions
const INCREASE = 'INCREASE';
const DECREASE = 'DECREASE';

// Offer actions
const FETCH_OFFER = 'FETCH_OFFER';
const FETCH_DETAIL_OFFER = 'FETCH_DETAIL_OFFER';

// Navigate actions
const NAVIGATE_OFFER = 'NAVIGATE_OFFER';
const NAVIGATE_DETAIL_OFFER = 'NAVIGATE_DETAIL_OFFER';

export default {
  INCREASE,
  DECREASE,
  LOGIN,
  LOGOUT,
  GET_USER_INFORMATION,
  LOGIN_LOADING,
  LOGIN_ERROR_REQUEST,
  FETCH_OFFER,
  FETCH_DETAIL_OFFER,
  NAVIGATE_OFFER,
  NAVIGATE_DETAIL_OFFER
};
